# Generated by Django 5.0 on 2024-08-26 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_todomodel_isdone'),
    ]

    operations = [
        migrations.AddField(
            model_name='todomodel',
            name='time',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
